export const GENRE_LABELS: Record<string, string> = {
  fantasy: 'ファンタジー',
  sf: 'SF',
  mystery: 'ミステリー',
  romance: '恋愛',
  horror: 'ホラー',
  literary: '純文学',
  adventure: '冒険',
  comedy: 'コメディ',
  drama: 'ヒューマンドラマ',
  historical: '歴史',
  modern: '現代・日常',
  youth: '青春',
  other: 'その他',
};
