/**
 * Post-processing for experience scripts generated by the two-stage pipeline.
 * Pure functions — no dependencies on DB, API, or NestJS.
 * Testable without mocks.
 */

export interface CharacterInfo {
  id: string;
  name: string;
  role: string | null;
  personality: string | null;
}

export interface PostProcessResult {
  fixedConnections: number;
  fixedRefs: number;
  fixedDeadEnds: number;
  normalizedSpeakers: number;
}

/**
 * Build episode -> scene ID mapping from scene keys.
 */
export function buildEpisodeMap(sceneIds: string[]): Record<number, string[]> {
  const epScenes: Record<number, string[]> = {};
  for (const sid of sceneIds) {
    const m = sid.match(/^ep(\d+)_/);
    if (m) {
      const ep = parseInt(m[1]);
      if (!epScenes[ep]) epScenes[ep] = [];
      epScenes[ep].push(sid);
    }
  }
  return epScenes;
}

/**
 * Find first and last scene of each episode by traversing continues chains.
 */
export function findEpisodeBoundaries(
  scenes: Record<string, any>,
  epScenes: Record<number, string[]>,
): { first: Record<number, string>; last: Record<number, string> } {
  const first: Record<number, string> = {};
  const last: Record<number, string> = {};

  for (const ep of Object.keys(epScenes).map(Number).sort((a, b) => a - b)) {
    const sids = epScenes[ep];
    if (!sids || sids.length === 0) continue;

    // Find scenes not targeted by any continues within same episode
    const continuedTo = new Set<string>();
    for (const sid of sids) {
      const cont = scenes[sid]?.continues;
      if (cont && cont.startsWith(`ep${ep}_`)) continuedTo.add(cont);
    }
    const roots = sids.filter(s => !continuedTo.has(s));
    first[ep] = roots[0] || sids[0];

    // Follow continues chain to find last
    let current = first[ep];
    const visited = new Set<string>();
    while (current && !visited.has(current)) {
      visited.add(current);
      const next = scenes[current]?.continues;
      if (next && next.startsWith(`ep${ep}_`) && scenes[next]) {
        current = next;
      } else {
        break;
      }
    }
    last[ep] = current;
  }

  return { first, last };
}

/**
 * P0: Fix inter-episode connections.
 * Ensures ep{N} last scene connects to ep{N+1} first scene.
 */
export function fixInterEpisodeConnections(
  scenes: Record<string, any>,
  totalEpisodes: number,
  epFirst: Record<number, string>,
  epLast: Record<number, string>,
): number {
  let fixed = 0;

  for (let ep = 1; ep < totalEpisodes; ep++) {
    const nextEp = ep + 1;
    const lastSid = epLast[ep];
    const nextFirstSid = epFirst[nextEp];
    if (!lastSid || !nextFirstSid) continue;

    const lastScene = scenes[lastSid];
    if (!lastScene) continue;

    const hasValidContinues = lastScene.continues && scenes[lastScene.continues];
    const hasValidAwareness = Array.isArray(lastScene.awareness) &&
      lastScene.awareness.some((a: any) => a.target && scenes[a.target]);

    if (!hasValidContinues && !hasValidAwareness) {
      const bridgeId = `ep${ep}_to_ep${nextEp}`;
      lastScene.continues = bridgeId;
      scenes[bridgeId] = {
        blocks: [{ type: 'scene-break', text: '* * *' }],
        continues: nextFirstSid,
      };
      fixed++;
    } else if (hasValidContinues && !lastScene.continues?.startsWith(`ep${nextEp}_`)) {
      // Check if continues chain eventually reaches next ep
      let reachesNext = false;
      let cur = lastScene.continues;
      const seen = new Set<string>();
      while (cur && !seen.has(cur) && scenes[cur]) {
        seen.add(cur);
        if (cur.startsWith(`ep${nextEp}_`)) { reachesNext = true; break; }
        cur = scenes[cur]?.continues;
      }
      if (!reachesNext) {
        // Find chain dead end and bridge it
        cur = lastScene.continues;
        const chainSeen = new Set<string>();
        while (cur && !chainSeen.has(cur) && scenes[cur]) {
          chainSeen.add(cur);
          const next = scenes[cur]?.continues;
          if (next && scenes[next]) { cur = next; } else { break; }
        }
        if (cur && scenes[cur]) {
          const bridgeId = `ep${ep}_to_ep${nextEp}`;
          scenes[cur].continues = bridgeId;
          scenes[bridgeId] = {
            blocks: [{ type: 'scene-break', text: '* * *' }],
            continues: nextFirstSid,
          };
          fixed++;
        }
      }
    }
  }

  return fixed;
}

/**
 * P0: Fix broken continues and awareness.target references.
 * Tries fuzzy name matching, then falls back to next episode's first scene.
 */
export function fixBrokenReferences(
  scenes: Record<string, any>,
  epFirst: Record<number, string>,
): number {
  let fixed = 0;

  for (const [sid, scene] of Object.entries(scenes)) {
    // Fix broken continues
    if (scene.continues && !scenes[scene.continues]) {
      const m = sid.match(/^ep(\d+)_/);
      if (m) {
        const ep = parseInt(m[1]);
        const targetName = scene.continues.replace(/^ep\d+_/, '');
        const candidates = Object.keys(scenes).filter(s =>
          (s.startsWith(`ep${ep}_`) || s.startsWith(`ep${ep + 1}_`)) &&
          s.includes(targetName)
        );
        if (candidates.length > 0) {
          scene.continues = candidates[0];
          fixed++;
        } else {
          const nextFirst = epFirst[ep + 1];
          if (nextFirst) {
            scene.continues = nextFirst;
            fixed++;
          } else {
            scene.continues = null;
          }
        }
      }
    }

    // Fix broken awareness targets
    if (Array.isArray(scene.awareness)) {
      for (const aw of scene.awareness) {
        if (aw.target && !scenes[aw.target]) {
          const m = sid.match(/^ep(\d+)_/);
          if (m) {
            const ep = parseInt(m[1]);
            const targetName = aw.target.replace(/^ep\d+_/, '');
            const candidates = Object.keys(scenes).filter(s =>
              (s.startsWith(`ep${ep}_`) || s.startsWith(`ep${ep + 1}_`)) &&
              s.includes(targetName)
            );
            if (candidates.length > 0) {
              aw.target = candidates[0];
              fixed++;
            } else {
              aw._broken = true;
            }
          }
        }
      }
      scene.awareness = scene.awareness.filter((a: any) => !a._broken);
    }
  }

  return fixed;
}

/**
 * P1: Fix dead-end scenes (no continues, no awareness) that aren't in the final episode.
 */
export function fixDeadEnds(
  scenes: Record<string, any>,
  epScenes: Record<number, string[]>,
  epFirst: Record<number, string>,
): number {
  let fixed = 0;
  const maxEp = Math.max(...Object.keys(epScenes).map(Number));

  for (const [sid, scene] of Object.entries(scenes)) {
    const m = sid.match(/^ep(\d+)_/);
    if (!m) continue;
    const ep = parseInt(m[1]);
    if (ep >= maxEp) continue;

    const hasContinues = scene.continues && scenes[scene.continues];
    const hasAwareness = Array.isArray(scene.awareness) && scene.awareness.length > 0;
    if (!hasContinues && !hasAwareness) {
      const nextFirst = epFirst[ep + 1];
      if (nextFirst) {
        const bridgeId = `${sid}_bridge`;
        scene.continues = bridgeId;
        scenes[bridgeId] = {
          blocks: [{ type: 'scene-break', text: '* * *' }],
          continues: nextFirst,
        };
        fixed++;
      }
    }
  }

  return fixed;
}

/**
 * P1: Normalize speaker names to canonical short form.
 */
export function normalizeSpeakers(
  scenes: Record<string, any>,
  characters: CharacterInfo[],
): number {
  const charInfo: { short: string; full: string; color: string }[] = [];
  for (const c of characters) {
    const short = c.name.split('（')[0].split('(')[0].trim().split(/[\s　]/)[0];
    let hash = 0;
    for (let i = 0; i < c.name.length; i++) hash = c.name.charCodeAt(i) + ((hash << 5) - hash);
    const hue = Math.abs(hash) % 360;
    charInfo.push({ short, full: c.name, color: `hsl(${hue}, 25%, 55%)` });
  }

  // Exact match map
  const speakerMap: Record<string, { canonical: string; color: string }> = {};
  for (const ci of charInfo) {
    speakerMap[ci.short] = { canonical: ci.short, color: ci.color };
    speakerMap[ci.full] = { canonical: ci.short, color: ci.color };
    const noSpace = ci.full.replace(/[\s　]/g, '');
    if (noSpace !== ci.full) speakerMap[noSpace] = { canonical: ci.short, color: ci.color };
  }

  const fuzzyMatch = (speaker: string): { canonical: string; color: string } | null => {
    const cleaned = speaker.replace(/[\uD800-\uDFFF\uFFFD]/g, '');
    if (speakerMap[cleaned]) return speakerMap[cleaned];

    for (const ci of charInfo) {
      if (ci.short.length >= 2 && (cleaned.includes(ci.short) || ci.short.includes(cleaned))) {
        return { canonical: ci.short, color: ci.color };
      }
      if (ci.full.includes(cleaned) || cleaned.includes(ci.full)) {
        return { canonical: ci.short, color: ci.color };
      }
    }

    for (const ci of charInfo) {
      const chars = new Set(ci.short);
      const overlap = [...cleaned].filter(ch => chars.has(ch)).length;
      if (overlap >= 2 && overlap >= ci.short.length * 0.5) {
        return { canonical: ci.short, color: ci.color };
      }
    }

    return null;
  };

  let normalized = 0;
  for (const scene of Object.values(scenes) as any[]) {
    for (const block of (scene.blocks || [])) {
      if (block.type === 'dialogue' && block.speaker) {
        let mapped: { canonical: string; color: string } | null = speakerMap[block.speaker] || null;
        if (!mapped) mapped = fuzzyMatch(block.speaker);

        if (mapped) {
          if (block.speaker !== mapped.canonical) {
            block.speaker = mapped.canonical;
            normalized++;
          }
          block.speakerColor = mapped.color;
        } else {
          block.speakerColor = block.speakerColor || 'hsl(0, 0%, 55%)';
        }
      }
    }
  }

  return normalized;
}

/**
 * P2: Fix intro awareness target if it points to a non-existent scene.
 */
export function fixIntroTarget(
  introData: any,
  scenes: Record<string, any>,
  epFirst: Record<number, string>,
): void {
  if (!introData) return;

  const fix = (aw: any) => {
    if (aw?.target && !scenes[aw.target]) {
      const first = epFirst[1];
      if (first) aw.target = first;
    }
  };

  if (Array.isArray(introData.awareness)) {
    introData.awareness.forEach(fix);
  } else if (introData.awareness) {
    fix(introData.awareness);
  }
}

/**
 * Split blocks that contain multiple paragraphs (separated by \n\n) into individual blocks.
 * Only applies to original, environment, and memory blocks. Dialogue and scene-break are untouched.
 */
export function splitMultiParagraphBlocks(scenes: Record<string, any>): number {
  const splittableTypes = new Set(['original', 'environment', 'memory']);
  let splitCount = 0;

  for (const scene of Object.values(scenes) as any[]) {
    if (!scene.blocks) continue;

    const newBlocks: any[] = [];
    for (const block of scene.blocks) {
      if (!splittableTypes.has(block.type) || !block.text?.includes('\n')) {
        newBlocks.push(block);
        continue;
      }

      // Split on double newlines (paragraph breaks)
      const paragraphs = block.text
        .split(/\n{1,}/)
        .map((p: string) => p.replace(/^[\s\u3000]+/, '').trim())
        .filter((p: string) => p.length > 0);

      if (paragraphs.length <= 1) {
        // No real split needed, just clean up the text
        block.text = paragraphs[0] || block.text.trim();
        newBlocks.push(block);
        continue;
      }

      for (const para of paragraphs) {
        newBlocks.push({ ...block, text: para });
      }
      splitCount++;
    }

    scene.blocks = newBlocks;
  }

  return splitCount;
}

/**
 * Run all post-processing steps on an experience script.
 */
export function postProcessExperienceScript(
  scenes: Record<string, any>,
  introData: any,
  totalEpisodes: number,
  characters: CharacterInfo[],
): PostProcessResult {
  const epScenes = buildEpisodeMap(Object.keys(scenes));
  const { first, last } = findEpisodeBoundaries(scenes, epScenes);

  const fixedConnections = fixInterEpisodeConnections(scenes, totalEpisodes, first, last);
  const fixedRefs = fixBrokenReferences(scenes, first);
  const fixedDeadEnds = fixDeadEnds(scenes, epScenes, first);
  const normalizedSpeakers = normalizeSpeakers(scenes, characters);
  splitMultiParagraphBlocks(scenes);
  fixIntroTarget(introData, scenes, first);

  return { fixedConnections, fixedRefs, fixedDeadEnds, normalizedSpeakers };
}
